### ISSUE TITLE
feat: UX request - make it easier way to see the NFTs in your wallet

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/RealmsWorld#200]
### Describe the feature you'd like to request

1. Allow one click viewing of L1 and L2 NFTs from the 'collections' section, if your wallet is already connected.
- current UX (clicking 'assets' in right hand pop out pane) is really hard to find
- can we either have a button to 'my assets' in the collection area OR have a filter 'held by wallet'  
 
2. when you land on your wallet normally the page is sparse (see image) as few hold golden tokens. Instead can we show all assets held by wallet as default

<img width="1440" alt="image" src="https://github.com/BibliothecaDAO/RealmsWorld/assets/102318873/e93deeb6-b0f2-41c2-8686-1a8c95704aa5">

### Describe the solution you'd like to see

describer above

### Additional information

none

**Comment by Xaxxoo** [comment]
Hi @LordSecretive, Kindly assign this to me. I will like to handle it.

**Comment by Dprof-in-tech** [comment]
Hello @LordSecretive , please i would love to work on this, could you assign it to me?

**Comment by Ugo-X** [comment]
Hello, good afternoon @LordSecretive. My name is Ugo and I am a full-stack dev. I would love to contribute to this effort, please can I be assigned to this task🥹

**Comment by Ugo-X** [comment]
> Hello, good afternoon @LordSecretive. My name is Ugo and I am a full-stack dev. I would love to contribute to this effort, please can I be assigned to this task🥹

@RedBeardEth

**Comment by Dprof-in-tech** [comment]
HI @LordSecretive , could i please be assigned to this task? I would love to contribute to this project

**Comment by armandocodecr** [comment]
Hello @LordSecretive , I would love to be part of this project so I am interested in solving this issue. Could you assign it to me?

I think I have good ideas to improve the interface as described in the issue. Also, I will be asking for feedback of my changes to the project community and to the Dojo Coding community of which I am part and where several members of this community contribute to this project and several other projects on Only Dust.

This in order to generate the best results before making the PR. 
First of all I would like to be honest with my availability in case you consider me to solve this issue. From Monday to Thursday I don't have much time to dedicate to solve this issue for several reasons. But from Friday to Sunday if I have availability of many more hours to dedicate them to the issue to solve and to be able to generate the contribution.

Best regards! Stay tuned for any update
